//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

public class StochasticRule : IComparable
{
	public float probability;
	public LRule rule;
	
	public StochasticRule ()
	{
		probability = -100000000.0f;
	}

	public int CompareTo(object obj){
		if(obj == null){
			return 1;
		}
		
		StochasticRule rhs = obj as StochasticRule;
		
		if(rhs != null){
			return this.probability.CompareTo(rhs.probability);
		} else {
			throw new ArgumentException("Object is not a Symbol");
		}
	}

	public StochasticRule maxRule(StochasticRule rhs){
		if(this.probability >= rhs.probability){
			return this;
		} else {
			return rhs;
		}
	}
}