//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;
using System.Collections.Generic;

public class Symbol : IComparable
{
	public char symbol;
	public List<LRule> rules;

	public Symbol ()
	{
		this.symbol = '0';
		this.rules = new List<LRule>();
	}

	public int CompareTo(object obj){
		if(obj == null){
			return 1;
		}

		Symbol rhs = obj as Symbol;

		if(rhs != null){
			return this.symbol.CompareTo(rhs.symbol);
		} else {
			throw new ArgumentException("Object is not a Symbol");
        }
	}
}

